### ISSUE TITLE
flg pls

### ISSUE THREAD

**Issue by om3rcitak** [nusu/zurna#1]

**Comment by om3rcitak** [comment]
flag is `GoP_{n3_k4d4qr_guz3l_b1r_fl4g}`

**Comment by berkbadem** [comment]
real flag is GoP_{g3rc3k_fl4g}

**Comment by nusu** [comment]
It will be an spotify helper which works in LAN, only os x btw.
Someone on the LAN should download and run it than zurna 😈  will gave the ip and port for other participant to access.
There will be a form which able to add a song to order.
I did it because everytime one of our teammates gets the dj thing we had to listen him/her song and It's bad for concentration, and youtube full of ads we hate it plus most of the time quality is sick

everything is ready, I'm on the UI part of the zurna 😈 .
